### ISSUE TITLE
反馈：文档搜索没结果

### ISSUE THREAD

**Issue by WuHuaJi0** [laravel-china/laravel-docs#358]
在 https://d.laravel-china.org/docs/5.5 中搜索内容，无论输入什么关键词，都没结果，不只是algolia的问题，还是别的。

附一个搜索请求包，这里我搜的是：[路由]：
curl 'https://fu55rwgndn-dsn.algolia.net/1/indexes/docs/query?x-algolia-api-key=c41c5de31ca55044dbb0bde815d35121&x-algolia-application-id=FU55RWGNDN&x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%203.7.7' -H 'Pragma: no-cache' -H 'Origin: https://d.laravel-china.org' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4,fr;q=0.2,la;q=0.2,co;q=0.2,de;q=0.2,nb;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded' -H 'accept: application/json' -H 'Cache-Control: no-cache' -H 'Referer: https://d.laravel-china.org/docs/5.5' -H 'Connection: keep-alive' --data '{"params":"query=%E8%B7%AF%E7%94%B1&hitsPerPage=5&tagFilters=%5B%225.5%22%5D"}' --compressed

**Comment by ElfSundae** [comment]
应该是站长没更新 algolia 的 key

```js
var algolia_app_id      = '8BB87I11DE';
var algolia_search_key  = '8e1d446d61fce359f69cd7c8b86a50de';
var version             = '5.5';
```

我这个可以搜索 https://laravel.0x123.com/zh 用的就是上面的 key

**Comment by ElfSundae** [comment]
@WuHuaJi0  https://d.laravel-china.org 搜索已经好了 🎉

**Comment by WuHuaJi0** [comment]
好的 ，多谢了
