### ISSUE TITLE
5.5 Blade 模板引擎 #继承布局 缺少关键代码

### ISSUE THREAD

**Issue by NekoArwen** [laravel-china/laravel-docs#366]
[原文档地址](https://laravel.com/docs/5.5/blade#template-inheritance)
[Laravel-china文档错误地方的地址](https://d.laravel-china.org/docs/5.5/blade#继承布局)
![image](https://user-images.githubusercontent.com/20843709/31985126-9c9c98ae-b996-11e7-8313-2f87f8ca077f.png)
![image](https://user-images.githubusercontent.com/20843709/31985157-afad7e90-b996-11e7-8c9a-179dbd441faf.png)

**Comment by JokerLinly** [comment]
已更正，谢谢🌹
