### ISSUE TITLE
blade一文代码翻译问题

### ISSUE THREAD

**Issue by TonyLianLong** [laravel-china/laravel-docs#381]
blade一文中
![image](https://user-images.githubusercontent.com/1451234/33351598-652c5878-d4df-11e7-9892-de42be270049.png)
上图代码中的文字翻译了一半
![image](https://user-images.githubusercontent.com/1451234/33351609-7e6f1e9c-d4df-11e7-9d3e-9aa351ec56b6.png)
上图部分则没有翻译
是否有必要统一翻译此处文字？
[Blade](https://d.laravel-china.org/docs/5.5/blade)

**Comment by JokerLinly** [comment]
其实一般我都不大想翻译代码里面的内容😄毕竟翻译成中文只是为了方便阅读，而不是因为大家都看不懂。
